/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salonso1602.obligatorio2_equipo3;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Néstor
 */
public class Programa extends javax.swing.JFrame {

    private static int nroCPUs;
    private static int quantum;
    private static Planificador planificador;

    /**
     * Creates new form Ejecutable
     *
     * @param NumCPUS
     * @param Quantum
     */
    public Programa(int NumCPUS, int Quantum) {
        quantum = Quantum;
        nroCPUs = NumCPUS;
        planificador = new Planificador(nroCPUs, quantum);
        initComponents();
        //Display_Todo.setVisible(false);

    }
    public static int id = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar_Frame = new javax.swing.JFrame();
        Volver_Agregar = new javax.swing.JButton();
        Label_Nombre_Proceso = new javax.swing.JLabel();
        Label_Tiempo_Total = new javax.swing.JLabel();
        Label_Periodo_ES = new javax.swing.JLabel();
        Label_Tiempo_ES = new javax.swing.JLabel();
        Label_Procesos_Creados = new javax.swing.JLabel();
        Tiempo_Dentro_ES = new javax.swing.JTextField();
        Cant_Procesos_Creados = new javax.swing.JTextField();
        Nombre_Proceso = new javax.swing.JTextField();
        Periodo_ES = new javax.swing.JTextField();
        Tiempo_Ejecucion = new javax.swing.JTextField();
        Crear_Procesos = new javax.swing.JButton();
        Label_Nombre_Proceso1 = new javax.swing.JLabel();
        Prioridad_Proceso = new javax.swing.JTextField();
        Es_Usuario = new javax.swing.JRadioButton();
        Es_SO = new javax.swing.JRadioButton();
        Bloquear_Frame = new javax.swing.JFrame();
        Bloqueo_Volver = new javax.swing.JButton();
        Label_Bloqueo_Colas = new javax.swing.JLabel();
        Label_Bloqueo_Procesos = new javax.swing.JLabel();
        Label_Bloqueo_Bloqueados = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Bloqueo_Procesos = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        Bloqueo_ProcBloq = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        Bloqueo_EnCPU = new javax.swing.JTextArea();
        Label_Bloqueo_CPU = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        Bloqueo_Colas = new javax.swing.JList<>();
        Bloqueo_BloquearProceso = new javax.swing.JButton();
        Bloqueo_DesbloquearProceso = new javax.swing.JButton();
        Label_Bloqueo_Procesos1 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        desbloqueables = new javax.swing.JList<>();
        Setup_Modificar_Frame = new javax.swing.JFrame();
        Volver_Modificar = new javax.swing.JButton();
        IrAModificarQuantum_Boton = new javax.swing.JButton();
        IrAModificarPrioridad_Boton = new javax.swing.JButton();
        GrupoBotonesSOoUser = new javax.swing.ButtonGroup();
        Display_Frame = new javax.swing.JFrame();
        Volver_Display = new javax.swing.JButton();
        botStart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaColas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaProcs = new javax.swing.JList<>();
        getProcData = new javax.swing.JButton();
        getFullCola = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cantQuantums = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        dispProcBloq = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        dispProcCPU = new javax.swing.JTextArea();
        Modificar_Prioridad_Frame = new javax.swing.JFrame();
        Label_ModificarProceso_Bloqueados = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        ModificarProcesos_Procesos = new javax.swing.JList<>();
        ModificarProceso_Boton = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        ModificarProcesos_ProcesosBloqueados = new javax.swing.JTextArea();
        ModificarProceso_Volver = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        ModificarProcesos_EnCPU = new javax.swing.JTextArea();
        Label_ModificarProceso_CPU = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        ModificarProcesos_Colas = new javax.swing.JList<>();
        Label_ModificarProceso_Colas = new javax.swing.JLabel();
        Label_ModificarProceso_Procesos = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ModificarProceso_PrioridadText = new javax.swing.JTextField();
        Modificar_Quantum_Frame = new javax.swing.JFrame();
        Label_Quantum_CPUs = new javax.swing.JLabel();
        ModificarQuantum_Text = new javax.swing.JTextField();
        ModificarQuantum_Boton = new javax.swing.JButton();
        ModificarQuantum_Volver = new javax.swing.JButton();
        Agregar_Proceso = new javax.swing.JButton();
        Bloquear_Proceso = new javax.swing.JButton();
        Modificar_Proceso = new javax.swing.JButton();
        Display_Todo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        Agregar_Frame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Agregar_Frame.setTitle("Agregar Proceso");
        Agregar_Frame.setMinimumSize(new java.awt.Dimension(800, 600));
        Agregar_Frame.setName("Agregar_Frame"); // NOI18N
        Agregar_Frame.setPreferredSize(new java.awt.Dimension(800, 800));
        Agregar_Frame.setSize(Display_Frame.getPreferredSize());

        Volver_Agregar.setText("Volver");
        Volver_Agregar.setActionCommand("");
        Volver_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver_AgregarActionPerformed(evt);
            }
        });

        Label_Nombre_Proceso.setText("Nombre del Proceso creado:");

        Label_Tiempo_Total.setText("Tiempo total de ejecución:");

        Label_Periodo_ES.setText("¿Cada cuánto tiempo realiza una E/S?");

        Label_Tiempo_ES.setText("Tiempo realizando la E/S:");

        Label_Procesos_Creados.setText("Cantidad de procesos a crearse:");

        Crear_Procesos.setText("Crear");
        Crear_Procesos.setActionCommand("");
        Crear_Procesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_ProcesosActionPerformed(evt);
            }
        });

        Label_Nombre_Proceso1.setText("Prioridad del Proceso:");

        GrupoBotonesSOoUser.add(Es_Usuario);
        Es_Usuario.setText("Usuario");

        GrupoBotonesSOoUser.add(Es_SO);
        Es_SO.setText("SO");

        javax.swing.GroupLayout Agregar_FrameLayout = new javax.swing.GroupLayout(Agregar_Frame.getContentPane());
        Agregar_Frame.getContentPane().setLayout(Agregar_FrameLayout);
        Agregar_FrameLayout.setHorizontalGroup(
            Agregar_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar_FrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Agregar_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Agregar_FrameLayout.createSequentialGroup()
                        .addComponent(Label_Periodo_ES)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                        .addComponent(Periodo_ES, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Agregar_FrameLayout.createSequentialGroup()
                        .addGroup(Agregar_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Tiempo_Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_Nombre_Proceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(Agregar_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nombre_Proceso, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(Tiempo_Ejecucion)))
                    .addComponent(Volver_Agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Crear_Procesos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Agregar_FrameLayout.createSequentialGroup()
                        .addGroup(Agregar_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Tiempo_ES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_Procesos_Creados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_Nombre_Proceso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(Agregar_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cant_Procesos_Creados, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(Tiempo_Dentro_ES)
                            .addComponent(Prioridad_Proceso, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(Agregar_FrameLayout.createSequentialGroup()
                        .addGroup(Agregar_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Es_Usuario)
                            .addComponent(Es_SO))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Agregar_FrameLayout.setVerticalGroup(
            Agregar_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Agregar_FrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Agregar_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Nombre_Proceso)
                    .addComponent(Nombre_Proceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Agregar_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Tiempo_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tiempo_Ejecucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Agregar_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Periodo_ES, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Periodo_ES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Agregar_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Tiempo_ES, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tiempo_Dentro_ES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Agregar_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Nombre_Proceso1)
                    .addComponent(Prioridad_Proceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Es_SO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Es_Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Agregar_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Procesos_Creados)
                    .addComponent(Cant_Procesos_Creados, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(Crear_Procesos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Volver_Agregar)
                .addGap(21, 21, 21))
        );

        Bloquear_Frame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Bloquear_Frame.setTitle("Bloquear Proceso");
        Bloquear_Frame.setMinimumSize(new java.awt.Dimension(800, 600));
        Bloquear_Frame.setName("Bloquear_Frame"); // NOI18N
        Bloquear_Frame.setPreferredSize(new java.awt.Dimension(800, 800));
        Bloquear_Frame.setSize(Display_Frame.getPreferredSize());

        Bloqueo_Volver.setText("Volver");
        Bloqueo_Volver.setActionCommand("");
        Bloqueo_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bloqueo_VolverActionPerformed(evt);
            }
        });

        Label_Bloqueo_Colas.setText("Colas de Prioridad");

        Label_Bloqueo_Procesos.setText("Procesos en Cola");

        Label_Bloqueo_Bloqueados.setText("Procesos Bloqueados");

        jScrollPane6.setViewportView(Bloqueo_Procesos);

        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Bloqueo_ProcBloq.setEditable(false);
        Bloqueo_ProcBloq.setColumns(20);
        Bloqueo_ProcBloq.setRows(5);
        jScrollPane7.setViewportView(Bloqueo_ProcBloq);

        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Bloqueo_EnCPU.setEditable(false);
        Bloqueo_EnCPU.setColumns(20);
        Bloqueo_EnCPU.setRows(5);
        jScrollPane8.setViewportView(Bloqueo_EnCPU);

        Label_Bloqueo_CPU.setText("Proceso en CPU/s");

        jScrollPane9.setViewportView(Bloqueo_Colas);

        Bloqueo_BloquearProceso.setText("Bloquear");
        Bloqueo_BloquearProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bloqueo_BloquearProcesoActionPerformed(evt);
            }
        });

        Bloqueo_DesbloquearProceso.setText("Desbloquear");
        Bloqueo_DesbloquearProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bloqueo_DesbloquearProcesoActionPerformed(evt);
            }
        });

        Label_Bloqueo_Procesos1.setText("Procesos Desbloqueables");

        jScrollPane14.setViewportView(desbloqueables);

        javax.swing.GroupLayout Bloquear_FrameLayout = new javax.swing.GroupLayout(Bloquear_Frame.getContentPane());
        Bloquear_Frame.getContentPane().setLayout(Bloquear_FrameLayout);
        Bloquear_FrameLayout.setHorizontalGroup(
            Bloquear_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Bloquear_FrameLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(Bloquear_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Bloquear_FrameLayout.createSequentialGroup()
                        .addGroup(Bloquear_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Label_Bloqueo_Colas)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(Bloquear_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Label_Bloqueo_Procesos)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(Bloqueo_BloquearProceso, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Bloquear_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(Bloqueo_DesbloquearProceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_Bloqueo_Procesos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(Bloqueo_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(Bloquear_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Bloqueo_CPU)
                    .addGroup(Bloquear_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Label_Bloqueo_Bloqueados, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        Bloquear_FrameLayout.setVerticalGroup(
            Bloquear_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Bloquear_FrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Bloquear_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Bloquear_FrameLayout.createSequentialGroup()
                        .addGroup(Bloquear_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Bloqueo_Colas)
                            .addComponent(Label_Bloqueo_Procesos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Bloquear_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                            .addComponent(jScrollPane6)
                            .addComponent(jScrollPane14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Bloquear_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bloqueo_DesbloquearProceso)
                            .addComponent(Bloqueo_BloquearProceso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bloqueo_Volver))
                    .addGroup(Bloquear_FrameLayout.createSequentialGroup()
                        .addGroup(Bloquear_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Bloqueo_CPU)
                            .addComponent(Label_Bloqueo_Procesos1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Label_Bloqueo_Bloqueados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)))
                .addContainerGap(287, Short.MAX_VALUE))
        );

        Setup_Modificar_Frame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Setup_Modificar_Frame.setTitle("Modificar Proceso");
        Setup_Modificar_Frame.setMinimumSize(new java.awt.Dimension(800, 600));
        Setup_Modificar_Frame.setName("Setup_Modificar_Frame"); // NOI18N
        Setup_Modificar_Frame.setPreferredSize(new java.awt.Dimension(800, 800));
        Setup_Modificar_Frame.setSize(Display_Frame.getPreferredSize());

        Volver_Modificar.setText("Volver");
        Volver_Modificar.setActionCommand("");
        Volver_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver_ModificarActionPerformed(evt);
            }
        });

        IrAModificarQuantum_Boton.setText("Modificar Quantum");
        IrAModificarQuantum_Boton.setActionCommand("");
        IrAModificarQuantum_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrAModificarQuantum_BotonActionPerformed(evt);
            }
        });

        IrAModificarPrioridad_Boton.setText("Modificar Procesos");
        IrAModificarPrioridad_Boton.setActionCommand("");
        IrAModificarPrioridad_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrAModificarPrioridad_BotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Setup_Modificar_FrameLayout = new javax.swing.GroupLayout(Setup_Modificar_Frame.getContentPane());
        Setup_Modificar_Frame.getContentPane().setLayout(Setup_Modificar_FrameLayout);
        Setup_Modificar_FrameLayout.setHorizontalGroup(
            Setup_Modificar_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Setup_Modificar_FrameLayout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addGroup(Setup_Modificar_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IrAModificarPrioridad_Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IrAModificarQuantum_Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Volver_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        Setup_Modificar_FrameLayout.setVerticalGroup(
            Setup_Modificar_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Setup_Modificar_FrameLayout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addComponent(IrAModificarPrioridad_Boton)
                .addGap(18, 18, 18)
                .addComponent(IrAModificarQuantum_Boton)
                .addGap(18, 18, 18)
                .addComponent(Volver_Modificar)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        Display_Frame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Display_Frame.setTitle("Display de Procesos");
        Display_Frame.setMinimumSize(new java.awt.Dimension(800, 600));
        Display_Frame.setName("marcoDisp"); // NOI18N
        Display_Frame.setPreferredSize(new java.awt.Dimension(800, 800));
        Display_Frame.setSize(Display_Frame.getPreferredSize());
        Display_Frame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                Display_FrameWindowClosed(evt);
            }
        });

        Volver_Display.setText("Volver");
        Volver_Display.setActionCommand("");
        Volver_Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver_DisplayActionPerformed(evt);
            }
        });

        botStart.setText("Iniciar");
        botStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botStartActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listaColas);

        jLabel1.setText("Colas de Prioridad");

        jLabel2.setText("Procesos en Cola");

        jScrollPane2.setViewportView(listaProcs);

        getProcData.setText("Ver Datos");
        getProcData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getProcDataActionPerformed(evt);
            }
        });

        getFullCola.setText("Cola de Listos");
        getFullCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getFullColaActionPerformed(evt);
            }
        });

        jLabel3.setText("Proceso en CPU/s");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Ejecutador de Rondas de Planificador");

        jLabel5.setText("Rondas a Ejecutar (cant de quantums):");

        cantQuantums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantQuantumsActionPerformed(evt);
            }
        });

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane3.setViewportView(txtLog);

        jLabel6.setText("Procesos Bloqueados");

        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        dispProcBloq.setEditable(false);
        dispProcBloq.setColumns(20);
        dispProcBloq.setRows(5);
        jScrollPane4.setViewportView(dispProcBloq);

        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        dispProcCPU.setEditable(false);
        dispProcCPU.setColumns(20);
        dispProcCPU.setRows(5);
        jScrollPane5.setViewportView(dispProcCPU);

        javax.swing.GroupLayout Display_FrameLayout = new javax.swing.GroupLayout(Display_Frame.getContentPane());
        Display_Frame.getContentPane().setLayout(Display_FrameLayout);
        Display_FrameLayout.setHorizontalGroup(
            Display_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Display_FrameLayout.createSequentialGroup()
                .addGroup(Display_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Display_FrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Display_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(Display_FrameLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(Display_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(Display_FrameLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(Display_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Display_FrameLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(Display_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGroup(Display_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Display_FrameLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(getProcData))
                            .addGroup(Display_FrameLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(getFullCola))))
                    .addGroup(Display_FrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Display_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Display_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cantQuantums, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Display_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Volver_Display)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        Display_FrameLayout.setVerticalGroup(
            Display_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Display_FrameLayout.createSequentialGroup()
                .addGroup(Display_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Display_FrameLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(Display_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Display_FrameLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(27, 27, 27)
                                .addGroup(Display_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(getProcData))
                                .addGap(9, 9, 9)
                                .addComponent(cantQuantums, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(Display_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(botStart)
                                    .addComponent(getFullCola))
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Display_FrameLayout.createSequentialGroup()
                                .addGroup(Display_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(6, 6, 6)
                                .addGroup(Display_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Volver_Display))
                    .addGroup(Display_FrameLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Modificar_Prioridad_Frame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Modificar_Prioridad_Frame.setMinimumSize(new java.awt.Dimension(800, 600));
        Modificar_Prioridad_Frame.setPreferredSize(new java.awt.Dimension(800, 800));
        Modificar_Prioridad_Frame.setSize(Display_Frame.getPreferredSize());

        Label_ModificarProceso_Bloqueados.setText("Procesos Bloqueados");

        jScrollPane10.setViewportView(ModificarProcesos_Procesos);

        ModificarProceso_Boton.setText("Modificar");
        ModificarProceso_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarProceso_BotonActionPerformed(evt);
            }
        });

        jScrollPane11.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        ModificarProcesos_ProcesosBloqueados.setEditable(false);
        ModificarProcesos_ProcesosBloqueados.setColumns(20);
        ModificarProcesos_ProcesosBloqueados.setRows(5);
        jScrollPane11.setViewportView(ModificarProcesos_ProcesosBloqueados);

        ModificarProceso_Volver.setText("Volver");
        ModificarProceso_Volver.setActionCommand("");
        ModificarProceso_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarProceso_VolverActionPerformed(evt);
            }
        });

        jScrollPane12.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        ModificarProcesos_EnCPU.setEditable(false);
        ModificarProcesos_EnCPU.setColumns(20);
        ModificarProcesos_EnCPU.setRows(5);
        jScrollPane12.setViewportView(ModificarProcesos_EnCPU);

        Label_ModificarProceso_CPU.setText("Proceso en CPU/s");

        jScrollPane13.setViewportView(ModificarProcesos_Colas);

        Label_ModificarProceso_Colas.setText("Colas de Prioridad");

        Label_ModificarProceso_Procesos.setText("Procesos en Cola");

        jLabel12.setText("Nueva prioridad del Proceso:");

        ModificarProceso_PrioridadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarProceso_PrioridadTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Modificar_Prioridad_FrameLayout = new javax.swing.GroupLayout(Modificar_Prioridad_Frame.getContentPane());
        Modificar_Prioridad_Frame.getContentPane().setLayout(Modificar_Prioridad_FrameLayout);
        Modificar_Prioridad_FrameLayout.setHorizontalGroup(
            Modificar_Prioridad_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Modificar_Prioridad_FrameLayout.createSequentialGroup()
                .addGroup(Modificar_Prioridad_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Modificar_Prioridad_FrameLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Modificar_Prioridad_FrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Label_ModificarProceso_Colas)))
                .addGroup(Modificar_Prioridad_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Modificar_Prioridad_FrameLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Label_ModificarProceso_Procesos))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Modificar_Prioridad_FrameLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(Modificar_Prioridad_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Modificar_Prioridad_FrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Modificar_Prioridad_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ModificarProceso_Boton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Modificar_Prioridad_FrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ModificarProceso_PrioridadText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)))
                .addGroup(Modificar_Prioridad_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Modificar_Prioridad_FrameLayout.createSequentialGroup()
                        .addComponent(Label_ModificarProceso_Bloqueados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Modificar_Prioridad_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Modificar_Prioridad_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_ModificarProceso_CPU)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(97, 97, 97))
            .addGroup(Modificar_Prioridad_FrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ModificarProceso_Volver, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
        Modificar_Prioridad_FrameLayout.setVerticalGroup(
            Modificar_Prioridad_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Modificar_Prioridad_FrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Modificar_Prioridad_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Modificar_Prioridad_FrameLayout.createSequentialGroup()
                        .addGroup(Modificar_Prioridad_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_ModificarProceso_Colas)
                            .addComponent(Label_ModificarProceso_Procesos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Modificar_Prioridad_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                            .addComponent(jScrollPane10))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Modificar_Prioridad_FrameLayout.createSequentialGroup()
                        .addComponent(Label_ModificarProceso_CPU)
                        .addGap(34, 34, 34)
                        .addGroup(Modificar_Prioridad_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Modificar_Prioridad_FrameLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(ModificarProceso_PrioridadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(ModificarProceso_Boton)))
                        .addGap(36, 36, 36)
                        .addComponent(Label_ModificarProceso_Bloqueados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(ModificarProceso_Volver)
                .addGap(361, 361, 361))
        );

        Modificar_Quantum_Frame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Modificar_Quantum_Frame.setMinimumSize(new java.awt.Dimension(800, 600));
        Modificar_Quantum_Frame.setPreferredSize(new java.awt.Dimension(800, 800));
        Modificar_Quantum_Frame.setSize(Display_Frame.getPreferredSize());

        Label_Quantum_CPUs.setText("Quantum:");

        ModificarQuantum_Boton.setText("Cambiar Quantum");
        ModificarQuantum_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarQuantum_BotonActionPerformed(evt);
            }
        });

        ModificarQuantum_Volver.setText("Volver");
        ModificarQuantum_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarQuantum_VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Modificar_Quantum_FrameLayout = new javax.swing.GroupLayout(Modificar_Quantum_Frame.getContentPane());
        Modificar_Quantum_Frame.getContentPane().setLayout(Modificar_Quantum_FrameLayout);
        Modificar_Quantum_FrameLayout.setHorizontalGroup(
            Modificar_Quantum_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Modificar_Quantum_FrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Modificar_Quantum_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ModificarQuantum_Volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModificarQuantum_Boton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Modificar_Quantum_FrameLayout.createSequentialGroup()
                        .addComponent(Label_Quantum_CPUs)
                        .addGap(18, 18, 18)
                        .addComponent(ModificarQuantum_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        Modificar_Quantum_FrameLayout.setVerticalGroup(
            Modificar_Quantum_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Modificar_Quantum_FrameLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(Modificar_Quantum_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Quantum_CPUs)
                    .addComponent(ModificarQuantum_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ModificarQuantum_Boton)
                .addGap(18, 18, 18)
                .addComponent(ModificarQuantum_Volver)
                .addContainerGap(283, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Obligatorio SO Equipo 6");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Ejecutable"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 800));
        setSize(Display_Frame.getPreferredSize());

        Agregar_Proceso.setText("Agregar Procesos");
        Agregar_Proceso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregar_Proceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_ProcesoActionPerformed(evt);
            }
        });

        Bloquear_Proceso.setText("Bloquear Procesos");
        Bloquear_Proceso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bloquear_Proceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bloquear_ProcesoActionPerformed(evt);
            }
        });

        Modificar_Proceso.setText("Modificar Procesos");
        Modificar_Proceso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Modificar_Proceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar_ProcesoActionPerformed(evt);
            }
        });

        Display_Todo.setText("Simulador");
        Display_Todo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Display_Todo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Display_TodoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Simulador de Planificador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Agregar_Proceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bloquear_Proceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Modificar_Proceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Display_Todo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(259, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(81, 81, 81)
                .addComponent(Agregar_Proceso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bloquear_Proceso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Modificar_Proceso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Display_Todo)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Agregar_ProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_ProcesoActionPerformed
        Agregar_Frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Agregar_ProcesoActionPerformed

    private void Bloquear_ProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bloquear_ProcesoActionPerformed
        Bloquear_Frame.setVisible(true);
        this.setVisible(false);
        
        Bloqueo_Colas.setModel(new DefaultComboBoxModel<String>(planificador.printListaPrioridades()));
        Bloqueo_Procesos.setModel(new DefaultComboBoxModel<String>(new String[0]));
        desbloqueables.setModel(new DefaultComboBoxModel<String>(planificador.printBloqueadosUser()));
        Bloqueo_ProcBloq.setText(planificador.printAllBloqueados());
        Bloqueo_EnCPU.setText(planificador.printProcsEnCPU());

        Bloqueo_Colas.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    if (Bloqueo_Colas.getSelectedValue() != null) {
                        String selected = Bloqueo_Colas.getSelectedValue().toString();

                        Bloqueo_Procesos.setModel(new DefaultComboBoxModel<String>(planificador.printProcEnCola(selected)));
                    }
                }
            }
        });
        dispProcBloq.setText(planificador.printAllBloqueados());
        dispProcCPU.setText(planificador.printProcsEnCPU());
    }//GEN-LAST:event_Bloquear_ProcesoActionPerformed

    private void Modificar_ProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar_ProcesoActionPerformed
        Setup_Modificar_Frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Modificar_ProcesoActionPerformed

    private void Volver_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver_AgregarActionPerformed
        this.setVisible(true);
        Agregar_Frame.setVisible(false);
    }//GEN-LAST:event_Volver_AgregarActionPerformed

    private void Volver_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver_ModificarActionPerformed
        this.setVisible(true);
        Setup_Modificar_Frame.setVisible(false);
    }//GEN-LAST:event_Volver_ModificarActionPerformed

    private void Crear_ProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_ProcesosActionPerformed
        if (Integer.parseInt(Cant_Procesos_Creados.getText()) <= 0) {
            JOptionPane.showMessageDialog(null, "La cantidad de procesos a crearse debe ser mayor o igual a 1", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            for (int i = 0; i < Integer.parseInt(Cant_Procesos_Creados.getText()); i++) {
                boolean SO;
                if (GrupoBotonesSOoUser.isSelected(Es_SO.getModel())) {
                    SO = true;
                } else {
                    SO = false;
                }
                Proceso nuevoProceso = new Proceso(Nombre_Proceso.getText(), Integer.parseInt(Prioridad_Proceso.getText()), Integer.parseInt(Tiempo_Ejecucion.getText()), Integer.parseInt(Periodo_ES.getText()), Integer.parseInt(Tiempo_Dentro_ES.getText()), String.valueOf(id), SO);
                id++;
                planificador.agregarProcesoAListos(nuevoProceso);
            }
            JOptionPane.showMessageDialog(null, "Se crearon los procesos con éxito", "Creación Exitosa", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Crear_ProcesosActionPerformed

    private void Display_TodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Display_TodoActionPerformed
        this.setVisible(false);
        Display_Frame.setVisible(true);

        listaColas.setModel(new DefaultComboBoxModel<String>(planificador.printListaPrioridades()));
        listaProcs.setModel(new DefaultComboBoxModel<>());

        listaColas.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    if (listaColas.getSelectedValue() != null) {
                        String selected = listaColas.getSelectedValue().toString();

                        listaProcs.setModel(new DefaultComboBoxModel<String>(planificador.printProcEnCola(selected)));
                    }
                }
            }
        });
    }//GEN-LAST:event_Display_TodoActionPerformed

    private void Display_FrameWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Display_FrameWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_Display_FrameWindowClosed

    private void cantQuantumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantQuantumsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantQuantumsActionPerformed

    private void getFullColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getFullColaActionPerformed
        JOptionPane.showMessageDialog(null, planificador.printListos(), "Cola", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_getFullColaActionPerformed

    private void getProcDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getProcDataActionPerformed
        if (listaProcs != null && listaColas != null) {
            String id = listaProcs.getSelectedValue().split(":")[1];
            Proceso proc = planificador.getProcEnCola(Integer.parseInt(listaColas.getSelectedValue()), id);
            JOptionPane.showMessageDialog(null, proc.getData(), proc.getNombre(), JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_getProcDataActionPerformed

    private void botStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botStartActionPerformed
        int repes = Integer.parseInt(cantQuantums.getText());
        planificador.ejecutarRonda(repes);
        dispProcBloq.setText(planificador.printAllBloqueados());
        dispProcCPU.setText(planificador.printProcsEnCPU());

        txtLog.setText(planificador.getLog());
    }//GEN-LAST:event_botStartActionPerformed

    private void Volver_DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver_DisplayActionPerformed
        this.setVisible(true);
        Display_Frame.setVisible(false);
    }//GEN-LAST:event_Volver_DisplayActionPerformed

    private void Bloqueo_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bloqueo_VolverActionPerformed
        this.setVisible(true);
        Bloquear_Frame.setVisible(false);
    }//GEN-LAST:event_Bloqueo_VolverActionPerformed

    private void IrAModificarQuantum_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrAModificarQuantum_BotonActionPerformed
        Setup_Modificar_Frame.setVisible(false);
        Modificar_Quantum_Frame.setVisible(true);
    }//GEN-LAST:event_IrAModificarQuantum_BotonActionPerformed

    private void IrAModificarPrioridad_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrAModificarPrioridad_BotonActionPerformed
        Setup_Modificar_Frame.setVisible(false);
        Modificar_Prioridad_Frame.setVisible(true);
        
        ModificarProcesos_Colas.setModel(new DefaultComboBoxModel<String>(planificador.printListaPrioridades()));
        ModificarProcesos_Procesos.setModel(new DefaultComboBoxModel<String>());

        ModificarProcesos_Colas.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    if (ModificarProcesos_Colas.getSelectedValue() != null) {
                        String selected = ModificarProcesos_Colas.getSelectedValue().toString();

                        ModificarProcesos_Procesos.setModel(new DefaultComboBoxModel<String>(planificador.printProcEnCola(selected)));
                    }
                }
            }
        });
        ModificarProcesos_ProcesosBloqueados.setText(planificador.printAllBloqueados());
        ModificarProcesos_EnCPU.setText(planificador.printProcsEnCPU());
    }//GEN-LAST:event_IrAModificarPrioridad_BotonActionPerformed

    private void Bloqueo_BloquearProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bloqueo_BloquearProcesoActionPerformed
        String IDaBloquear = Bloqueo_Procesos.getSelectedValue().split(":")[1];
        Proceso procesoABloquear = planificador.getProc(IDaBloquear);
        if(procesoABloquear == null)
        {
            JOptionPane.showMessageDialog(null, "No se encontró el proceso que indicaste, por favor, intentalo de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            procesoABloquear.BloquearProceso();
            JOptionPane.showMessageDialog(null, "El proceso se bloqueará en la próxima ronda", "Done", JOptionPane.OK_OPTION);
            Bloqueo_ProcBloq.setText(planificador.printAllBloqueados());
        }
    }//GEN-LAST:event_Bloqueo_BloquearProcesoActionPerformed

    private void Bloqueo_DesbloquearProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bloqueo_DesbloquearProcesoActionPerformed
        String IDaDesbloquear = desbloqueables.getSelectedValue().split(":")[1];
        Proceso procesoADesbloquear = planificador.getProcEnBloq(IDaDesbloquear);
        if(procesoADesbloquear == null)
        {
            JOptionPane.showMessageDialog(null, "No se encontró el proceso que indicaste, por favor, intentalo de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            procesoADesbloquear.DesbloquearProceso();
            JOptionPane.showMessageDialog(null, "El proceso se desbloqueará en la próxima ronda", "Done", JOptionPane.OK_OPTION);
            Bloqueo_ProcBloq.setText(planificador.printAllBloqueados());
        }
    }//GEN-LAST:event_Bloqueo_DesbloquearProcesoActionPerformed

    private void ModificarQuantum_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarQuantum_BotonActionPerformed
        if(Integer.parseInt(ModificarQuantum_Text.getText())<=0)
        {
            JOptionPane.showMessageDialog(null, "La cantidad de Quantum a asignar a la CPU debe ser mayor o igual a 1", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            planificador.setQuantum(Integer.parseInt(ModificarQuantum_Text.getText()));
            JOptionPane.showMessageDialog(null, "Quantum modificado correctamente", "Modificación Exitosa", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ModificarQuantum_BotonActionPerformed

    private void ModificarQuantum_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarQuantum_VolverActionPerformed
        Modificar_Quantum_Frame.setVisible(false);
        Setup_Modificar_Frame.setVisible(true);
    }//GEN-LAST:event_ModificarQuantum_VolverActionPerformed

    private void ModificarProceso_PrioridadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarProceso_PrioridadTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarProceso_PrioridadTextActionPerformed

    private void ModificarProceso_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarProceso_VolverActionPerformed
        Modificar_Prioridad_Frame.setVisible(false);
        Setup_Modificar_Frame.setVisible(true);
    }//GEN-LAST:event_ModificarProceso_VolverActionPerformed

    private void ModificarProceso_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarProceso_BotonActionPerformed
        String IDaModificar = ModificarProcesos_Procesos.getSelectedValue().split(":")[1];
        Proceso procesoAModificar = planificador.getProc(IDaModificar);
        if(procesoAModificar == null)
        {
            JOptionPane.showMessageDialog(null, "No se encontró el proceso que indicaste, por favor, intentalo de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            ModificarProcesos_Procesos.setModel(new DefaultComboBoxModel<>());
            if(Integer.parseInt(ModificarProceso_PrioridadText.getText())<=0)
            {
                JOptionPane.showMessageDialog(null, "La cantidad de Prioridad a asignar a un Proceso debe ser mayor o igual a 1", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(Integer.parseInt(ModificarProceso_PrioridadText.getText())>99)
            {
                JOptionPane.showMessageDialog(null, "La cantidad de Prioridad a asignar a un Proceso debe ser menor o igual a 99", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                procesoAModificar.setPrioridad(Integer.parseInt(ModificarProceso_PrioridadText.getText()));
                planificador.updateProceso(procesoAModificar);
                JOptionPane.showMessageDialog(null, "Proceso modificado correctamente", "Modificación Exitosa", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_ModificarProceso_BotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programa(nroCPUs, quantum).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Agregar_Frame;
    private javax.swing.JButton Agregar_Proceso;
    private javax.swing.JFrame Bloquear_Frame;
    private javax.swing.JButton Bloquear_Proceso;
    private javax.swing.JButton Bloqueo_BloquearProceso;
    private javax.swing.JList<String> Bloqueo_Colas;
    private javax.swing.JButton Bloqueo_DesbloquearProceso;
    private javax.swing.JTextArea Bloqueo_EnCPU;
    private javax.swing.JTextArea Bloqueo_ProcBloq;
    private javax.swing.JList<String> Bloqueo_Procesos;
    private javax.swing.JButton Bloqueo_Volver;
    private javax.swing.JTextField Cant_Procesos_Creados;
    private javax.swing.JButton Crear_Procesos;
    private javax.swing.JFrame Display_Frame;
    private javax.swing.JButton Display_Todo;
    private javax.swing.JRadioButton Es_SO;
    private javax.swing.JRadioButton Es_Usuario;
    private javax.swing.ButtonGroup GrupoBotonesSOoUser;
    private javax.swing.JButton IrAModificarPrioridad_Boton;
    private javax.swing.JButton IrAModificarQuantum_Boton;
    private javax.swing.JLabel Label_Bloqueo_Bloqueados;
    private javax.swing.JLabel Label_Bloqueo_CPU;
    private javax.swing.JLabel Label_Bloqueo_Colas;
    private javax.swing.JLabel Label_Bloqueo_Procesos;
    private javax.swing.JLabel Label_Bloqueo_Procesos1;
    private javax.swing.JLabel Label_ModificarProceso_Bloqueados;
    private javax.swing.JLabel Label_ModificarProceso_CPU;
    private javax.swing.JLabel Label_ModificarProceso_Colas;
    private javax.swing.JLabel Label_ModificarProceso_Procesos;
    private javax.swing.JLabel Label_Nombre_Proceso;
    private javax.swing.JLabel Label_Nombre_Proceso1;
    private javax.swing.JLabel Label_Periodo_ES;
    private javax.swing.JLabel Label_Procesos_Creados;
    private javax.swing.JLabel Label_Quantum_CPUs;
    private javax.swing.JLabel Label_Tiempo_ES;
    private javax.swing.JLabel Label_Tiempo_Total;
    private javax.swing.JButton ModificarProceso_Boton;
    private javax.swing.JTextField ModificarProceso_PrioridadText;
    private javax.swing.JButton ModificarProceso_Volver;
    private javax.swing.JList<String> ModificarProcesos_Colas;
    private javax.swing.JTextArea ModificarProcesos_EnCPU;
    private javax.swing.JList<String> ModificarProcesos_Procesos;
    private javax.swing.JTextArea ModificarProcesos_ProcesosBloqueados;
    private javax.swing.JButton ModificarQuantum_Boton;
    private javax.swing.JTextField ModificarQuantum_Text;
    private javax.swing.JButton ModificarQuantum_Volver;
    private javax.swing.JFrame Modificar_Prioridad_Frame;
    private javax.swing.JButton Modificar_Proceso;
    private javax.swing.JFrame Modificar_Quantum_Frame;
    private javax.swing.JTextField Nombre_Proceso;
    private javax.swing.JTextField Periodo_ES;
    private javax.swing.JTextField Prioridad_Proceso;
    private javax.swing.JFrame Setup_Modificar_Frame;
    private javax.swing.JTextField Tiempo_Dentro_ES;
    private javax.swing.JTextField Tiempo_Ejecucion;
    private javax.swing.JButton Volver_Agregar;
    private javax.swing.JButton Volver_Display;
    private javax.swing.JButton Volver_Modificar;
    private javax.swing.JButton botStart;
    private javax.swing.JTextField cantQuantums;
    private javax.swing.JList<String> desbloqueables;
    private javax.swing.JTextArea dispProcBloq;
    private javax.swing.JTextArea dispProcCPU;
    private javax.swing.JButton getFullCola;
    private javax.swing.JButton getProcData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JList<String> listaColas;
    private javax.swing.JList<String> listaProcs;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
